create table TB_AUDITORIA_VENDA
(
    id_auditoria number generated by default as identity not null,
    id_venda number not null,
    usuario varchar2(10) not null,
    usuario_bd varchar2(128) not null,
    dt_evento timestamp not null,
    detalhes varchar2(4000),

    -- constraints
        -- pk
        constraint pk_tb_auditoria_venda primary key(id_auditoria),

        -- fk
        constraint fk_tb_auditoria_venda foreign key(id_venda)
            references TB_VENDA (id_venda)
);

-- index
create index ix_auditoria_venda on tb_auditoria_venda(id_venda);