create table TB_VENDA
(
    id_venda number generated by default as identity not null,
    id_cliente number not null,
    id_vendedor number not null,
    dt_venda date not null,
    status varchar2(20) not null,
    canal varchar2(20) not null,
    valor_bruto number(14,2) not null,
    desconto_total number(14,2) not null,
    valor_liquido number(14,2) not null,

    -- constraints
        -- pk
        constraint pk_tb_venda primary key(id_venda),

        -- fk
        constraint fk_tb_venda_cliente foreign key(id_cliente) references TB_CLIENTE (id_cliente),
        constraint fk_tb_venda_vendedor foreign key(id_vendedor) references TB_VENDEDOR (id_vendedor)
);

-- index
create index ix_venda_dt_venda on tb_venda(dt_venda);
create index ix_venda_cliente on tb_venda(id_cliente);
create index ix_venda_vendedor on tb_venda(id_vendedor);
