CREATE TABLE TB_VENDA_ITEM
(
    id_item NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_venda NUMBER NOT NULL,
    id_produto NUMBER NOT NULL,
    quantidade NUMBER(10,0) CHECK (quantidade > 0) NOT NULL,
    preco_unit NUMBER(12,2) NOT NULL,
    desconto_item NUMBER(12,2) DEFAULT 0 NOT NULL,
    valor_total NUMBER(14,2)

    CONSTRAINT pk_tb_venda_item
        PRIMARY KEY (id_item),

    CONSTRAINT fk_tb_item_venda
        FOREIGN KEY (id_venda)
        REFERENCES TB_VENDA (id_venda)
        ON DELETE CASCADE,

    CONSTRAINT fk_tb_item_produto
        FOREIGN KEY (id_produto)
        REFERENCES TB_PRODUTO (id_produto)
);

CREATE INDEX ix_item_venda
ON TB_VENDA_ITEM(id_venda);

CREATE INDEX ix_item_produto
ON TB_VENDA_ITEM(id_produto);