CREATE TABLE TB_CLIENTE
(
    id_cliente NUMBER GENERATED BY DEFAULT AS IDENTITY /*PRIMARY KEY ($)*/,
    nome VARCHAR2(120) NOT NULL,
    email VARCHAR2(120) NOT NULL,
    cpf VARCHAR2(11) NOT NULL,
    telefone VARCHAR2(20) NOT NULL,
    dt_cadastro DATE NOT NULL,
    ativo CHAR(1) DEFAULT 'S' CHECK (ativo IN ('S', 'N')) NOT NULL,

    -- ($): a constraint pode ser criada direto na linha escrevento PRIMARY KEY ou UNIQUE no final, por exemplo,
    -- mas escrever separado assim é mais organizado e há a possibilidade de dar um nome à constraint:

    -- PK 
    CONSTRAINT pk_tb_cliente PRIMARY KEY(id_cliente),

    -- UNIQUES
    CONSTRAINT uq_tb_cliente_email UNIQUE(email),
    CONSTRAINT uq_tb_cliente_cpf UNIQUE(cpf)
);