create table TB_PRODUTO
(
    id_produto number generated by default as identity not null,
    id_categoria number not null,
    sku varchar2(30) not null,
    nome varchar(120) not null,
    preco_unit number(12,2) check (preco_unit > 0) not null,
    ativo char (1) default 'S' check (ativo in ('S', 'N')) not null,
    dt_cadastro date,

    -- constraints
        -- pk
        constraint pk_tb_produto primary key(id_produto),

        -- uq
        constraint uq_tb_produto_sku unique(sku),

        -- fk
        constraint fk_tb_produto_categoria foreign key(id_categoria) references TB_CATEGORIA (id_categoria)
);

-- index
create index ix_prod_categoria on tb_produto(id_categoria);