CREATE TABLE TB_VENDEDOR
(
    id_vendedor NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(120) NOT NULL,
    dt_admissao DATE not null,
    ativo CHAR(1) DEFAULT 'S' CHECK (ativo IN ('S', 'N')) NOT NULL,

    -- CONSTRAINTS
        -- PK
        constraint pk_tb_vendedor primary key(id_vendedor),

        -- UQ
        constraint uq_tb_vendedor_email unique(email)
);