create table TB_CATEGORIA
(
    id_categoria NUMBER generated by default as identity,
    nome varchar2(80) not null,

    -- contsrainst
        -- pk
        constraint pk_tb_categoria primary key(id_categoria),

        -- uq
        constraint uq_tb_categoria_nome unique(nome)
);